travis:
  secure:
    BINSTAR_TOKEN: iyGpe+hlsHo5t6PxG/1tiKsp89d1RfY34Bjii4QyUf66AOVNtkOEn3uIZSgxXPbGBpJCrm1bBaYOAN3RkhYx9O1R5DaKcmEKXlTPwuIr9RqBDcAjJq7Jq6ECQIlTSnTuZsGl2ApryUUxlB11ZjtgK9H5U20j8lf5F5SfzraTxbprY8Bip/awfWsWw9knlWbGoOVctz9Fza4VvF+NismJ3Va/9QN7oa4BQbMkpMqBrp7BQmN17+7L7P/tRy7ujh/svxbp9fGZHWulzVz9d4ltZ8EV4OwGv733GniJCqiAirQV/5Ys3CfDULug6OHvVU8w1sTgmSDaUmNATFtsSq0VENptQTsQICCNJa/hWABlIiu7nP9EhDhNpLgQGvgoTYQBWybyrb3kQVNdB2ZLiQscv0LODr5vphnyR3GjxXAsI4Nh22eHPTcCA+MEZVj+1BoBZVZ1urmdJ04Zccyq3uLwnSN5StZjx6VUuvgl6Myb/xNW25catDmnW5qI5UkSYKVCPrNKEm1xtJihDNHuncGoG7bOOTLd/zzhSHJz+ncruuFwCJjAlH97iGIsCU06Xe05+k2S26YKjlFTrMbscdJnNouhCFupmVHSy20ovRvHFquWnUKXU0pjQCTE5LZeyVE8PoHFFI2kJwPoiZy/HG8utt0gm4nznp4BZ7Xpwrq4gm4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
