travis:
  secure:
    BINSTAR_TOKEN: PhJMT/QtU85QKN9hCaOXRFQ2t7Qo9Le0/sjIrINEwACFr8J+XxHBMkgZBsvuZIFskW7z4ve7IPsaYQsLmrcDrUlqsLzBAk4BPmWnoPkdgkMtQHjEK+u5801/WgcAO7tMKiKonpQBMdzsQAfhsqcuhNvQGlFzUBmCmqGZY0hSRa3H3e8TkZoSEjjAEF0nQxbVAghy8hkYSZu3YBBx6cQ9IAXVVTgycKYvrEg7uRMEPdPpo4Mrh686E5Yez/FUPqiiTZn5QcCVDyOWJB4ICIWSnM7LNuk2DDGv8pqQoHk34s7OHo9sYLQbvm1EOCmU9SZOE4iWo7JMNrHZtwOx3genhVwIliA/714qSI2XmOA2mrkjviDFktZudpUaj2jqvpFBWid6BzE7RsN8O7GBI0NTr2oT+qc/3KumOhKjiaOr+kIilaPCUCDBao/DCKf4JQGbw/4P8kNtRGmHLDfFUDEEbtp0ypFmQJz3nWKflU4J0hK+5LiejgrhBhDIQJw6fRsvnsDYSt2WkrrpltzEgLf0qc7hMtt/7lDPZR8Onoe+tNKMvt5n7yY6q1qVP++G7ch7fesQf29tfF4NfpGUFvEEjtcP5gvWj8jHWEmSzYnKVBx+Zp3vcirt8ZbMT6B28bIs8b2DX0rE6Ouy8u9TqQrXdeBNm7SEbVldc6Wg8rMFh+s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
